name: event_planner
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  charts_flutter: ^0.12.0
  table_calendar: ^3.0.5
  flutter:
      sdk: flutter
  provider: ^6.0.0
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/
